$(document).ready(function(){$('.header-mobile-menu').click(function(){$('.header-menu').toggle();});$("#owl-slider").owlCarousel({autoPlay:true,items:8,autoheight:true,lazyLoad:true,navigation:true,pagination:false,navigationText:["",""],itemsDesktop:[1160,5],itemsDesktopSmall:[992,4],itemsTablet:[768,3],itemsMobile:[479,2],slideSpeed:200,});$('body').append('<div id="top">Back to Top</div>');$(window).scroll(function(){if($(window).scrollTop()!=0){$('#top').fadeIn();}else{$('#top').fadeOut();}});$('#top').click(function(){$('body,html').animate({scrollTop:0},300);});$('.notification-popup').click(function(){$('.notification-popup').hide();});$('.notification-close').click(function(){$('.notification-popup').hide();});});function show_notication_popup(content){$(".notification-content").html(content);$('.notification-popup').show();}
function change_alias(alias){var str=alias;str=str.toLowerCase();str=str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g,"a");str=str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g,"e");str=str.replace(/ì|í|ị|ỉ|ĩ/g,"i");str=str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g,"o");str=str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g,"u");str=str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g,"y");str=str.replace(/đ/g,"d");str=str.replace(/ /g,"_");str=str.replace(/[^0-9a-z\s]/gi,'_');str=str.replace(/_+_/g,"_");str=str.replace(/^\_+|\_+$/g,"");return str;}
function trim(s,c){if(c==="]")c="\\]";if(c==="\\")c="\\\\";return s.replace(new RegExp("^["+c+"]+|["+c+"]+$","g"),"");}
$(document).ready(function(){$('.fb-comment-title').click(function(){if(!$(".fb-comment-title").hasClass("fb-comment-title-show")){fc_fb_comment_load('show');}
else{fc_fb_comment_load('hide');}});});$(document).ready(function(){if($.cookie("panel-fb-comment")){cookie_panel_fb_comment=$.cookie("panel-fb-comment");if(cookie_panel_fb_comment=='fb-comment-title-show'){fc_fb_comment_load('show');}
else if(cookie_panel_fb_comment=='fb-comment-title-hidden'){fc_fb_comment_load('hide');}}else{fc_fb_comment_load('show');}});var load_comment=0;function fc_fb_comment_load(result){if(!$('.fb-comments-content').length){return;}
load_comment++;if(result=='load'){cookie_panel_fb_comment=$.cookie("panel-fb-comment");if(cookie_panel_fb_comment=='fb-comment-title-hidden'){return;}}
if(result=='hide'){$(".fb-comments-content").html('');$(".fb-comment-title").removeClass("fb-comment-title-show");$(".fb-comment-title").addClass("fb-comment-title-hidden");var date=new Date();date.setTime(date.getTime()+(365*24*60*60*1000));$.cookie("panel-fb-comment","fb-comment-title-hidden",{expires:date,path:"/"});return;}
$(".fb-comment-title").addClass("fb-comment-title-show");$(".fb-comment-title").removeClass("fb-comment-title-hidden");var url_comment=$(".fb-comments-content").attr('id');url_comment=atob(url_comment);var str_comment='<div class="fb-comments" data-href="'+url_comment+'" data-width="100%" data-numposts="10" data-colorscheme="light"></div>';if($.cookie('changer-mode-dark')&&$.cookie('changer-mode-dark')=='yes'){str_comment='<div class="fb-comments" data-href="'+url_comment+'" data-width="100%" data-numposts="10" data-colorscheme="dark"></div>';}
$(".fb-comments-content").html(str_comment);if(load_comment>1){FB.XFBML.parse($('.commentsfab').get(0),function(){$(".FB_Loader").remove();});}
var date=new Date();date.setTime(date.getTime()+(365*24*60*60*1000));if(result=='show'){var date=new Date();date.setTime(date.getTime()+(365*24*60*60*1000));$.cookie("panel-fb-comment","fb-comment-title-show",{expires:date,path:"/"});}}