(function($){$.fn.fsearch=function(){var $searchInput=$(this);$searchInput.after('<div id="SearchResult"></div>');$resultDiv=$('#SearchResult');$searchInput.addClass('searchi');$resultDiv.html("<ul></ul><div id='search-footer' class='searchf'></div>");$old='';var timesearchstory=null;$searchInput.keyup(function(e){var q=$(this).val().trim();if(q!=''){if(q==$old||q.length<3)
return;if(q==$old&&e.keyCode!=13){if(e.keyCode==27){$searchInput.val('');$resultDiv.hide();}
return;}
$old=q;var current_index=$('.selected').index(),$options=$resultDiv.find('.option'),items_total=$options.length;$resultDiv.fadeIn();$resultDiv.find('#search-footer').html("<img src='"+baseurljs+"themes/hm/images/loading.gif' alt='Loading...'/>");if(timesearchstory!=null){clearTimeout(timesearchstory);}
timesearchstory=setTimeout(function(){timesearchstory=null;$.ajax({contentType:"application/x-www-form-urlencoded; charset=UTF-8",url:baseurljs+'getstorysearchjson',type:'POST',data:"searchword="+change_alias(q),dataType:"json",success:function(jsonResult){jsonResult_kw=jsonResult.link_search_by_kw;jsonResult_list=jsonResult.searchlist;var str='';for(var i=0;i<jsonResult_list.length;i++){str+='<a href="'+jsonResult_list[i].url_story+'"><li onmouseover="fmouseover('+jsonResult_list[i].id+');" id='+jsonResult_list[i].id+' class="option item">';str+='<img class="item_image" src="'+jsonResult_list[i].image+'" />';str+='<div class="item_panel_right">';str+='<span class="item_name">'+jsonResult_list[i].name+'</span>';if(jsonResult_list[i].author.trim()!=''){str+='<span class="item_author">'+jsonResult_list[i].author+'</span>';}
if(jsonResult_list[i].lastchapter.trim()!=''){str+='<span class="item_chapter" >'+jsonResult_list[i].lastchapter+'</span>';}
str+='</div></li></a>';}
$resultDiv.find('ul').empty().prepend(str);$search_panel="<p><a href='"+jsonResult_kw+"' style='color: #ff530d;' >Click here to view all results.</a></p>";if(jsonResult.length>0)
$resultDiv.find('div#search-footer').html("<p>Display first "+jsonResult.length+" results.</p>"+$search_panel);else
$resultDiv.find('div#search-footer').html("<p>No matches found. Try a different search...</p>"+$search_panel);}});},1000);}
else{$resultDiv.hide();}});jQuery(document).on("click",function(e){var $clicked=$(e.target);if($clicked.hasClass("searchi")||$clicked.hasClass("searchf")){}
else{$resultDiv.fadeOut();}});$searchInput.click(function(){var q=$(this).val();if(q!='')
{$resultDiv.fadeIn();}});};})(jQuery);$(document).ready(function(){var chk_search_story=document.getElementById('search-story');if(chk_search_story){$('#search-story').fsearch();jQuery(function($){jQuery('#search-story').keypress(function(event){if(event.which==13){window.location=$search_address+change_alias(chk_search_story.value);}})});$(".pn-search-btn").click(function(){window.location=$search_address+change_alias(chk_search_story.value);});};});function fmouseover(id){$(".option").removeClass("selected");document.getElementById(id).className+=" selected";}