obj_url_get_noti="https://user.mngusr.com/bookmark_get_notification";obj_url_get_list_idstory="https://user.mngusr.com/bookmark_get_list_idstory";obj_url_bookmark_get_list_full="https://user.mngusr.com/bookmark_get_list_full";obj_url_bookmark_add="https://user.mngusr.com/bookmark_add";obj_url_bookmark_delete='https://user.mngusr.com/bookmark_delete';obj_url_bookmark_update='https://user.mngusr.com/bookmark_update';obj_source='manganato';storage_name_lst_bm='lst-bookmark-storyid';function fun_get_noti(){$(document).ready(function(){$.ajax({url:obj_url_get_noti,type:"post",data:{user_data:glb_user_data,},success:function(data){obj_json=JSON.parse(data);if(obj_json.result=="ok"){obj_json.data=parseInt(obj_json.data);if(obj_json.data>0){$('.user-notification').html('<em class="user-notifications-num">'+obj_json.data+'</em>');}}
else{console.log("Error : bookmark_get_notification - "+data);}},error:function(jqXHR,exception){console.log("Error : bookmark_get_notification - "+ajax_check_error(jqXHR,exception));},});});};function fun_get_list_idstory_key(){$result="";$.ajax({url:obj_url_get_list_idstory,type:"post",async:false,data:{user_data:glb_user_data,},success:function(data){obj_json=JSON.parse(data);if(obj_json.result=="ok"){$result=obj_json.data;}
else{console.log("Error : bookmark_get_list_idstory - "+data);}},error:function(jqXHR,exception){console.log("Error : bookmark_get_list_idstory - "+ajax_check_error(jqXHR,exception));},});return $result;}
function fun_get_list_idstory_cache(){lst_id=",";if(typeof(Storage)==="undefined"){lst_id=fun_get_list_idstory_key();}
else{var date=new Date();var list_his=localStorage.getItem(storage_name_lst_bm);if(typeof list_his!=='undefined'&&list_his!=null&&list_his!=''){try{list_his_json=JSON.parse(list_his);list_his_json_timecreate=list_his_json.timecreate;if(typeof list_his_json_timecreate==='undefined'||list_his_json_timecreate<=date.getTime()-900000){localStorage.setItem(storage_name_lst_bm,'');list_his=localStorage.getItem(storage_name_lst_bm);}}catch(e){localStorage.setItem(storage_name_lst_bm,'');list_his=localStorage.getItem(storage_name_lst_bm);}}
if(typeof list_his==='undefined'||list_his==null||list_his==''){lst_id_temp=fun_get_list_idstory_key();lst_id_json=JSON.stringify({timecreate:date.getTime(),data:lst_id_temp});localStorage.setItem(storage_name_lst_bm,lst_id_json);list_his=localStorage.getItem(storage_name_lst_bm);lst_id=list_his;}
else{lst_id=list_his;}}
lst_id_fix="";try{lst_id_fix=JSON.parse(lst_id).data;}catch(e){}
return lst_id_fix;}
function fun_get_story_checkbookmark_icon(){lst_id_fix=fun_get_list_idstory_cache();$('.bookmark_check').each(function(index,element){if(lst_id_fix.indexOf(','+atob($(this).attr('data-id'))+',')>-1){$(this).append('<em class="item-bookmarked"></em>');}});}
function fun_get_bookmark_button(){$(document).ready(function(){$.ajax({url:obj_url_get_list_idstory,type:"post",data:{user_data:glb_user_data,},success:function(data){obj_json=JSON.parse(data);if(obj_json.result=="ok"){if(obj_json.data.indexOf(','+glb_story_id+',')>-1){$('.user_btn_follow_i').html('<i></i><a rel="nofollow" href="'+glb_bookmark_link+'" >Followed</a>');}
else{$('.user_btn_follow_i').append('<img onClick="fun_bookmark_add();" class="story-bookmark" src="themes/hm/images/bookmark.png" />');}}
else{console.log("Error : get_bookmark_button - "+data);}},error:function(jqXHR,exception){console.log("Error : get_bookmark_button - "+ajax_check_error(jqXHR,exception));},});});}
function fun_get_list_full_html(){$(document).ready(function(){$('.bookmark-content').html('<p style="background-color: #fff; padding: 10px;">Loading ...</p>');$.ajax({url:obj_url_bookmark_get_list_full,type:"post",data:{user_data:glb_user_data,bm_page:glb_bm_page,bm_source:obj_source,out_type:'html',},success:function(data){obj_json=JSON.parse(data);if(obj_json.result=="ok"){$('.bookmark-content').html(obj_json.data);}
else{$('.bookmark-content').html('<p style="background-color: #fff; padding: 10px;">'+obj_json.data+'</p>');console.log("Error : bookmark_get_list_full - "+data);}},error:function(jqXHR,exception){console.log("Error : bookmark_get_list_full - "+ajax_check_error(jqXHR,exception));},});});};isfollowed=false;function fun_bookmark_add(){$(document).ready(function(){if(isfollowed==true){return;}
if(glb_user_data==''){show_notication_popup('You need to log in to use this function.');return;}
isfollowed=true;$.ajax({url:obj_url_bookmark_add,type:"post",data:{user_data:glb_user_data,story_data:glb_story_data,},success:function(data){obj_json=JSON.parse(data);if(obj_json.result=="ok"){$(".user_btn_follow_i").html('<i></i><a rel="nofollow" href="'+glb_bookmark_link+'" >Followed</a>');localStorage.removeItem(storage_name_lst_bm);}
else{show_notication_popup(obj_json.data);console.log("Error : bookmark_add - "+data);}},error:function(jqXHR,exception){console.log("Error : bookmark_add - "+ajax_check_error(jqXHR,exception));},});});};isdeleted=false;function fun_bookmark_delete(glb_bm_data,glb_bm_id){$(document).ready(function(){if(isdeleted==true){return;}
if(glb_user_data==''){show_notication_popup('You need to log in to use this function.');return;}
isdeleted=true;$.ajax({url:obj_url_bookmark_delete,type:"post",data:{user_data:glb_user_data,bm_data:glb_bm_data,},success:function(data){obj_json=JSON.parse(data);if(obj_json.result=="ok"){$(".bm-it-"+glb_bm_id).hide('normal');localStorage.removeItem(storage_name_lst_bm);}
else{console.log('Error : bookmark_delete - '+data);}},error:function(jqXHR,exception){console.log('Error : bookmark_delete - '+ajax_check_error(jqXHR,exception));},});isdeleted=false;});};function fun_bookmark_update(){$(document).ready(function(){$.ajax({url:obj_url_bookmark_update,type:"post",data:{user_data:glb_user_data,story_data:glb_story_data,chapter_data:glb_chapter_data,},success:function(data){obj_json=JSON.parse(data);if(obj_json.result=="ok"){console.log("bookmark_update - ok");}
else{console.log("Error : bookmark_update - "+data);}},error:function(jqXHR,exception){console.log("Error : bookmark_update - "+ajax_check_error(jqXHR,exception));},});});};function timeconverter(timestamp,format){var a=new Date(timestamp*1);var months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];var year=a.getFullYear();var month=months[a.getMonth()];var date=a.getDate();var hour=a.getHours();var min=a.getMinutes();var sec=a.getSeconds();var time=date+' '+month+' - '+hour+':'+min;return time;}
function ajax_check_error(jqXHR,exception){var obj_msg='';if(jqXHR.status===0){obj_msg='Not connect. Verify Network.';}else if(jqXHR.status==404){obj_msg='Requested page not found. [404]';}else if(jqXHR.status==500){obj_msg='Internal Server Error [500].';}else if(exception==='parsererror'){obj_msg='Requested JSON parse failed.';}else if(exception==='timeout'){obj_msg='Time out error.';}else if(exception==='abort'){obj_msg='Ajax request aborted.';}else{obj_msg='Uncaught Error... '+jqXHR.responseText;}
return obj_msg;}